name: Test Build Anaconda3 and Miniconda3 Images
on:
  pull_request:
    paths:
      - 'anaconda3/**/Dockerfile'
      - 'miniconda3/**/Dockerfile'
      - '.github/workflows/ana_minconda_ci.yml'
  push:
    paths:
      - 'anaconda3/**/Dockerfile'
      - 'miniconda3/**/Dockerfile'
      - '.github/workflows/ana_minconda_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [anaconda3, miniconda3]
        base: [alpine, debian]
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          driver-opts: network=host

      - name: test-build ${{ matrix.type }}/${{ matrix.base }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.type }}/${{ matrix.base }}
          builder: ${{ steps.buildx.outputs.name }}
          file: ./${{ matrix.type }}/${{ matrix.base }}/Dockerfile
          tags: continuumio/${{ matrix.type }}/${{ matrix.base }}:latest
          push: false
